# Group By

O método groupby é o primeiro passo para fazer algum tipo de agregação de dados.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Database/drinks.csv')

In [3]:
df.groupby(by="continent")

In [4]:
df.groupby(by="continent").sum()

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,AlgeriaAngolaBeninBotswanaBurkina FasoBurundiC...,3258,878,0.75.91.15.44.36.34.04.05.83.80.40.11.72.31.10...
AS,AfghanistanBahrainBangladeshBhutanBruneiCambod...,1332,457,0.02.00.00.40.62.25.02.20.10.00.22.57.00.56.80...
EU,AlbaniaAndorraArmeniaAustriaAzerbaijanBelarusB...,8705,6057,4.912.43.89.71.314.410.54.610.310.28.211.810.4...
OC,AustraliaFijiKiribatiMarshall IslandsMicronesi...,1247,537,10.42.01.00.02.31.09.36.91.52.61.21.11.00.9
SA,ArgentinaBoliviaBrazilChileColombiaEcuadorGuya...,2101,820,8.33.87.27.64.24.27.17.36.15.66.67.7

In [5]:
df.groupby(by="continent")["wine_servings"].sum()

continent
AF     878
AS     457
EU    6057
OC     537
SA     820
Name: wine_servings, dtype: int64

In [6]:
numeric_columns = df.select_dtypes(include=[int, float]).columns

In [7]:
std_by_continent = df.groupby(by="continent")[numeric_columns].std()

In [8]:
std_by_continent

           beer_servings  wine_servings
continent
AF             80.231505      38.143812
AS             38.178838      27.872709
EU             99.422820      97.071578
OC             97.024552      66.897864
SA             65.242845      86.640672

In [9]:
df.loc[:,"Serve_Cerveja"] = df.beer_servings > 0
df

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol,continent,Serve_Cerveja
0,Afghanistan,0,0,0.0,AS,False
1,Albania,89,54,4.9,EU,True
2,Algeria,25,14,0.7,AF,True
3,Andorra,245,312,12.4,EU,True
4,Angola,217,45,5.9,AF,True
...,...,...,...,...,...,...
187,Venezuela,333,3,7.7,SA,True
188,Vietnam,111,1,2.0,AS,True
189,Yemen,6,0,0.1,AS,True
190,Zambia,32,19,2.5,AF,True
191,Zimbabwe,64,18,4.7,AF,True

# Apply

O método apply aplica uma função a cada item do eixo especificado.

In [10]:
df["country"]

0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
187      Venezuela
188        Vietnam
189          Yemen
190         Zambia
191       Zimbabwe
Name: country, Length: 192, dtype: object

In [11]:
df["beer_servings"] + 1

0        1
1       90
2       26
3      246
4      218
      ...
187    334
188    112
189      7
190     33
191     65
Name: beer_servings, Length: 192, dtype: int64

In [12]:
def exemplo(row):
    if row.continent == "EU":
        row.beeer_servings = - 1
    return row

df.apply(exemplo, axis=1)

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol,continent,Serve_Cerveja
0,Afghanistan,0,0,0.0,AS,False
1,Albania,89,54,4.9,EU,True
2,Algeria,25,14,0.7,AF,True
3,Andorra,245,312,12.4,EU,True
4,Angola,217,45,5.9,AF,True
...,...,...,...,...,...,...
187,Venezuela,333,3,7.7,SA,True
188,Vietnam,111,1,2.0,AS,True
189,Yemen,6,0,0.1,AS,True
190,Zambia,32,19,2.5,AF,True
191,Zimbabwe,64,18,4.7,AF,True

In [13]:
def exemplo(row):
    if row.continent == "EU":
        row["beeer_servings2"] = - 1
    return row

df.apply(exemplo, axis=1)

,Serve_Cerveja,beeer_servings2,beer_servings,continent,country,total_litres_of_pure_alcohol,wine_servings
0,False,NaN,0,AS,Afghanistan,0.0,0
1,True,-1.0,89,EU,Albania,4.9,54
2,True,NaN,25,AF,Algeria,0.7,14
3,True,-1.0,245,EU,Andorra,12.4,312
4,True,NaN,217,AF,Angola,5.9,45
...,...,...,...,...,...,...,...
187,True,NaN,333,SA,Venezuela,7.7,3
188,True,NaN,111,AS,Vietnam,2.0,1
189,True,NaN,6,AS,Yemen,0.1,0
190,True,NaN,32,AF,Zambia,2.5,19
191,True,NaN,64,AF,Zimbabwe,4.7,18

In [14]:
df["country"].apply(lambda x: x.upper())

0      AFGHANISTAN
1          ALBANIA
2          ALGERIA
3          ANDORRA
4           ANGOLA
          ...
187      VENEZUELA
188        VIETNAM
189          YEMEN
190         ZAMBIA
191       ZIMBABWE
Name: country, Length: 192, dtype: object

# Lambda Functions

Uma função Lambda é uma função anônima que recebe alguns parâmetros e executa apenas uma operação.

Uso:

lambda param_1, ..., param_n: operação

In [15]:
lambda  x:x ** 2

Mesmo a função sendo anônima, é possível atribuir seu valor a uma variável. Desta forma é possível executá-la. Entretanto, se é necessário executar a função normalmente, é recomendado criar a função de maneira tradicional, com def.

In [16]:
f = lambda  x:x ** 2
f(5)

25

In [17]:
df.head()

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol,continent,Serve_Cerveja
0,Afghanistan,0,0,0.0,AS,False
1,Albania,89,54,4.9,EU,True
2,Algeria,25,14,0.7,AF,True
3,Andorra,245,312,12.4,EU,True
4,Angola,217,45,5.9,AF,True

# Usando o apply com uma função lambda:

In [18]:
df.beer_servings.apply(lambda x: x ** 2)

0           0
1        7921
2         625
3       60025
4       47089
        ...
187    110889
188     12321
189        36
190      1024
191      4096
Name: beer_servings, Length: 192, dtype: int64

In [19]:
def soma(x, y):
    return x + y

df.beer_servings.apply(lambda x: soma(x, 5))

0        5
1       94
2       30
3      250
4      222
      ...
187    338
188    116
189     11
190     37
191     69
Name: beer_servings, Length: 192, dtype: int64

In [20]:
df.loc[:, "normed_beer_servings"] = df.beer_servings.apply(lambda x: soma(x, 5))
df.head()

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol,continent,Serve_Cerveja,normed_beer_servings
0,Afghanistan,0,0,0.0,AS,False,5
1,Albania,89,54,4.9,EU,True,94
2,Algeria,25,14,0.7,AF,True,30
3,Andorra,245,312,12.4,EU,True,250
4,Angola,217,45,5.9,AF,True,222

# Tratamento de exceções

Uma exceção é resultante de um erro durante a execução de um código Python. O tratamento de exceções permite que a execução de um código siga por um caminho alternativo, evitando que a execução "quebre" por conta de erros.

O fluxo de tratamento de exceções em Python segue o racional:

    try:
        pass
    except:
        pass
    finally:    # instrução opcional
        pass

O bloco try contém o código que pode gerar alguma exceção.

O bloco except realiza a tratativa da exceção. Esse bloco pode ou não especificar um erro. A vantagem de tratarmos os erros esperados individualmente é flexibilizar os caminhos de execução alternativos.

O bloco finally é opcional ao usarmos try/except e é executado sempre ao final dos demais blocos, ou seja, é executado independentemente se houve ou não uma exceção naquela execução.

In [21]:
def inverte(x):
    return 1 / x

df.beer_servings.apply(inverte)

ZeroDivisionError: division by zero

In [22]:
def inverte(x):
    try:
        return 1 / x
    except ZeroDivisionError:
        return 0

df.beer_servings.apply(inverte)

0      0.000000
1      0.011236
2      0.040000
3      0.004082
4      0.004608
         ...
187    0.003003
188    0.009009
189    0.166667
190    0.031250
191    0.015625
Name: beer_servings, Length: 192, dtype: float64

## Cuidado com erros que deveriam ser erros:

In [23]:
df.continent.apply(inverte)

TypeError: unsupported operand type(s) for /: 'int' and 'str'

Podemos ser um tanto **precisos**, para evitar capturas de erros diferentes:

In [24]:
def inverte(x):
    try:
        return 1 / x
    except ZeroDivisionError:
        return 0

df.beer_servings.astype(str).apply(inverte)

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [25]:
def inverte(x):
    try:
        return 1 / x
    except ZeroDivisionError:
        return 999

df.beer_servings.astype(str).apply(inverte)

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [26]:
df.beer_servings.apply(inverte)

0      999.000000
1        0.011236
2        0.040000
3        0.004082
4        0.004608
          ...
187      0.003003
188      0.009009
189      0.166667
190      0.031250
191      0.015625
Name: beer_servings, Length: 192, dtype: float64

# Applymap

O método applymap aplica uma função a todos os elementos de um dataaframe

In [27]:
def mult_10(x):
    if isinstance(x, float) or isinstance(x, int):
        return x * 10
    elif isinstance(x, str):
        return x.upper()
    else:
        return x

df.applymap(mult_10)

C:\Users\Romulo Vieira\AppData\Local\Temp\ipykernel_10488\1143086918.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(mult_10)

,country,beer_servings,wine_servings,total_litres_of_pure_alcohol,continent,Serve_Cerveja,normed_beer_servings
0,AFGHANISTAN,0,0,0.0,AS,0,50
1,ALBANIA,890,540,4.9,EU,10,940
2,ALGERIA,250,140,0.7,AF,10,300
3,ANDORRA,2450,3120,12.4,EU,10,2500
4,ANGOLA,2170,450,5.9,AF,10,2220
...,...,...,...,...,...,...,...
187,VENEZUELA,3330,30,7.7,SA,10,3380
188,VIETNAM,1110,10,2.0,AS,10,1160
189,YEMEN,60,0,0.1,AS,10,110
190,ZAMBIA,320,190,2.5,AF,10,370
191,ZIMBABWE,640,180,4.7,AF,10,690

# Combinando Dataframes

No Pandas existem 4 tipos de operações para combinar dataframes:

   - merge
   - join
   - concat
   - append

merge e join possuem basicamente o mesmo funcionamento. Da mesma maneira, concat e append também são redundantes.

Vamos falar com mais detalhe do fucnionamento do merge e concat.

## Importando os dados

In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('../Database/tips.csv')

In [30]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31  Female     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Merge

A função merge é usada para executar combinações complexas de colunas da mesma forma que o SQL.

Para fazer o merge, precisamos de dois dataframes:

In [31]:
tips = df.groupby(by=["sex", "smoker"])[["tip"]].sum()
bills = df.groupby(by=["sex", "smoker"])[["total_bill"]].sum()

In [32]:
tips

                 tip
sex    smoker
Female No      13.01
Male   No      15.10

In [33]:
bills

               total_bill
sex    smoker
Female No          107.18
Male   No           80.19

Ao executar o comando abaixo, podemos ver o que o merge tem diversos parâmetros. Todos eles são úteis, e vamos olhar com mais detalhe os mais importantes.

   - left: o dataframe que estará à esquerda no join.
   - right: o dataframe que estará à direita no join.
   - how: a maneira como será feito o join (inner, left, right, outer).
   - on: as colunas onde estão as chaves do join.
   - left_on: se os nomes das colunas dos chaves forem diferentes em cada dataframe, aqui são passados os nomes dessas colunas para o dataframe da esquerda.
   - right_on: a mesma coisa do parâmetro anterior, mas para o dataframe da direita.
   - left_index: se os valores de índices do dataframe da esquerda são as chaves, deve ser True. 
   - right_index: a mesma coisa do parâmetro anterior, mas para o dataframe da direita.
   - sort: ordena as chaves usadas no join.
   - suffixes: é possível passar uma tupla com 2 posições. Para as colunas com mesmo nome nos dois dataframes, adiciona o sufixo correspondente ao nome da coluna.
   - indicator: indica que tipo de merge foi feito em cada linha do dataframe.

In [34]:
pd.merge?

## Merge com índex

In [35]:
pd.merge(bills, tips, right_index=True, left_index=True)

               total_bill    tip
sex    smoker
Female No          107.18  13.01
Male   No           80.19  15.10

## Merge com colunas

In [36]:
bills.reset_index()

      sex smoker  total_bill
0  Female     No      107.18
1    Male     No       80.19

In [37]:
tips.reset_index()

      sex smoker    tip
0  Female     No  13.01
1    Male     No  15.10

In [38]:
pd.merge(bills.reset_index(), tips.reset_index(), on=["sex", "smoker"])

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

## Merge com index e colunas

In [39]:
pd.merge(bills.reset_index(), tips, left_on = ["sex", "smoker"], right_index=True)

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

## Left Join

In [40]:
tips

                 tip
sex    smoker
Female No      13.01
Male   No      15.10

In [41]:
tips.reset_index().head(2)

      sex smoker    tip
0  Female     No  13.01
1    Male     No  15.10

In [42]:
pd.merge(bills.reset_index(), tips.reset_index(), on=["sex", "smoker"], how="left")

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

In [43]:
pd.merge(bills.reset_index(), tips.reset_index(), on=["sex", "smoker"], how="right")

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

## Inner Join

In [44]:
tips.reset_index().head(2)

      sex smoker    tip
0  Female     No  13.01
1    Male     No  15.10

In [45]:
tips.reset_index().tail(3)

      sex smoker    tip
0  Female     No  13.01
1    Male     No  15.10

In [46]:
pd.merge(bills.reset_index().tail(3), tips.reset_index().head(2), on=["sex", "smoker"], how="inner")

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

## Outer Join

In [47]:
pd.merge(bills.reset_index().tail(3), tips.reset_index().head(2), on=["sex", "smoker"], how="outer")

      sex smoker  total_bill    tip
0  Female     No      107.18  13.01
1    Male     No       80.19  15.10

In [48]:
pd.merge(bills.reset_index().tail(3), tips.reset_index().head(2), on=["sex", "smoker"], how="outer", indicator=True)

      sex smoker  total_bill    tip _merge
0  Female     No      107.18  13.01   both
1    Male     No       80.19  15.10   both

In [49]:
aux = pd.merge(bills.reset_index().tail(3), tips.reset_index().head(2), on=["sex", "smoker"], how="outer", indicator=True)

aux

      sex smoker  total_bill    tip _merge
0  Female     No      107.18  13.01   both
1    Male     No       80.19  15.10   both

In [50]:
aux.loc[aux["_merge"] == "left_only"]

Empty DataFrame
Columns: [sex, smoker, total_bill, tip, _merge]
Index: []

## Usando Sufixos

In [51]:
pd.merge(left=bills, right=bills, right_index=True, left_index=True, suffixes=("_left", "_right"))

               total_bill_left  total_bill_right
sex    smoker
Female No               107.18            107.18
Male   No                80.19             80.19

In [52]:
left = pd.DataFrame({"a":[0, 0, 0, 0, 2, 3, 4, 5]})
right = pd.DataFrame({"b":[0, 0, 2, 3, 6, 7]})

pd.merge(left=left, right=right, left_on="a", right_on="b", how="outer")

      a    b
0   0.0  0.0
1   0.0  0.0
2   0.0  0.0
3   0.0  0.0
4   0.0  0.0
5   0.0  0.0
6   0.0  0.0
7   0.0  0.0
8   2.0  2.0
9   3.0  3.0
10  4.0  NaN
11  5.0  NaN
12  NaN  6.0
13  NaN  7.0

In [53]:
right

   b
0  0
1  0
2  2
3  3
4  6
5  7

## Concat

A função concat é utilizada para combinar linhas ou colunas de dois dataframes. A diferença é que concat permite apenas operações mais simples. Por isso, precisamos do merge para operações mais complexas.

## Adicionando linhas a um Dataframe

O parâmetro axis controla se a concatenação será feita por linhas ou colunas. Os valores possíveis são 0 ou "index" e 1 ou "columns". Por padrão, o valor é 0.

In [54]:
pd.concat?

In [55]:
bills

               total_bill
sex    smoker
Female No          107.18
Male   No           80.19

In [56]:
pd.concat([bills, bills, bills])

               total_bill
sex    smoker
Female No          107.18
Male   No           80.19
Female No          107.18
Male   No           80.19
Female No          107.18
Male   No           80.19

## Adicionando colunas a um Dataframe

Quando o concat é executado com o valor do parâmetro axis=1, as colunas dos dataframes são adicionadas e as linhas são combinadas de acordo com o índice.

In [57]:
pd.concat([bills, tips], axis=1)

               total_bill    tip
sex    smoker
Female No          107.18  13.01
Male   No           80.19  15.10

## Ignorando índices

Em alguns casos os valores dos índices dos dataframes são irrelevantes, nesses casos é possível utilizar o parâmetro ignore_index para que o índice não seja usado.

O parâmetro sort é usado para ordenar o eixo que não é usado na concatenação.

In [58]:
pd.concat([bills, tips], axis=1, ignore_index=True, sort=False)

                    0      1
sex    smoker
Female No      107.18  13.01
Male   No       80.19  15.10

In [59]:
pd.concat([bills, tips], axis=0, ignore_index=True, sort=False)

   total_bill    tip
0      107.18    NaN
1       80.19    NaN
2         NaN  13.01
3         NaN  15.10

In [60]:
pd.concat([bills, bills], axis=1, ignore_index=True)

                    0       1
sex    smoker
Female No      107.18  107.18
Male   No       80.19   80.19

## Usando Keys

É possível indexar cada parte (dataframe) concatenado utilizando o parâmetro keys.

In [61]:
pd.concat([bills, tips, bills, tips], sort=True, keys=["a", "b", "c", "d"])

                   tip  total_bill
  sex    smoker
a Female No        NaN      107.18
  Male   No        NaN       80.19
b Female No      13.01         NaN
  Male   No      15.10         NaN
c Female No        NaN      107.18
  Male   No        NaN       80.19
d Female No      13.01         NaN
  Male   No      15.10         NaN

In [62]:
pd.concat([bills, bills], axis=1, keys=["a", "b", "c", "d"])

C:\Users\Romulo Vieira\AppData\Local\Temp\ipykernel_10488\2192797539.py:1: FutureWarning: The behavior of pd.concat with len(keys) != len(objs) is deprecated. In a future version this will raise instead of truncating to the smaller of the two sequences
  pd.concat([bills, bills], axis=1, keys=["a", "b", "c", "d"])

                       a          b
              total_bill total_bill
sex    smoker
Female No         107.18     107.18
Male   No          80.19      80.19